<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net48</TargetFramework><LangVersion>latest</LangVersion><Optimize>false</Optimize></PropertyGroup><ItemGroup><Compile Include="../../SpecialPawnIdeologyCompatibility/SpecialPawnIdeology.cs" Link="SpecialPawnIdeology.cs"/><Reference Include="0Harmony"><HintPath>../../MP_MeowOnlineShop/Libs/0Harmony.dll</HintPath></Reference></ItemGroup></Project>
