<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework><LangVersion>latest</LangVersion>
    <AssemblyName>Meow.RaceTrioCompatibility</AssemblyName>
    <Version>1.1.4</Version>
    <GameRoot>G:/Steam/steamapps/common/RimWorld</GameRoot>
    <ReferenceRoot>../../BuildValidation/WolfeinSuite_20260906/Game/Mods</ReferenceRoot>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>$(GameRoot)/RimWorldWin64_Data/Managed/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameRoot)/RimWorldWin64_Data/Managed/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(GameRoot)/RimWorldWin64_Data/Managed/UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(GameRoot)/RimWorldWin64_Data/Managed/UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>../MP_MeowOnlineShop/Libs/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0MultiplayerAPI"><HintPath>../../../Multiplayer/1.6/Assemblies/0MultiplayerAPI.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="MP_MeowOnlineShop"><HintPath>../../1.6/Assemblies/MP_MeowOnlineShop.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
