<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Meow.RavenCompatibility</AssemblyName>
    <GameRoot Condition="'$(GameRoot)' == ''">G:/Steam/steamapps/common/RimWorld</GameRoot>
    <MultiplayerRoot Condition="'$(MultiplayerRoot)' == ''">$(MSBuildProjectDirectory)/../../../Multiplayer</MultiplayerRoot>
    <HarmonyRoot Condition="'$(HarmonyRoot)' == ''">$(MSBuildProjectDirectory)/../../../2009463077</HarmonyRoot>
    <OutputPath>../../BuildValidation/RavenRace_20260907/ProductionBuild/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>$(GameRoot)/RimWorldWin64_Data/Managed/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameRoot)/RimWorldWin64_Data/Managed/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(HarmonyRoot)/Current/Assemblies/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0MultiplayerAPI"><HintPath>$(MultiplayerRoot)/Assemblies/0MultiplayerAPI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Multiplayer"><HintPath>$(MultiplayerRoot)/AssembliesCustom/Multiplayer.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MultiplayerCommon"><HintPath>$(MultiplayerRoot)/AssembliesCustom/MultiplayerCommon.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
